version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "test"
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.com
      PGADMIN_DEFAULT_PASSWORD: pw
    volumes:
      - ./data/pgadmin/data:/var/lib/pgadmin
    depends_on:
      - postgres

  app:
    image: golang
    working_dir: /app/
    volumes:
      - .:/app
      - ${GOPATH:-./data/gopath}:/go
    command: go run .
    ports:
      - "80:80"
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_HOST: postgres
      SERVER_ADDRESS: ":80"
