version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB:

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.com
      PGADMIN_DEFAULT_PASSWORD: pw
    volumes:
      - ./data/pgadmin/data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - postgres
